site_name: MOCluGen Documentation
site_url: https://clugen.github.io/MOCluGen
repo_url: https://github.com/clugen/MOCluGen/
edit_uri: https://github.com/clugen/MOCluGen/edit/main/docs/docs/
site_description: Documentation for the MOCluGen MATLAB/Octave cluster
  generation toolbox
site_author: Nuno Fachada
copyright: <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="CC-BY License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a>

theme:
  name: material
  logo: https://github.com/clugen/.github/blob/main/logos/apple-touch-icon-120x120.png?raw=true
  favicon: https://raw.githubusercontent.com/clugen/.github/main/logos/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    primary: blue grey
    accent: deep purple
  features:
  - navigation.instant
  - navigation.expand
  - navigation.indexes
  - navigation.tabs
  - navigation.tabs.sticky
  - toc.integrate

plugins:
- search

markdown_extensions:
- attr_list
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.arithmatex:
    generic: true
- toc:
    toc_depth: 3
    permalink: true

extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# extra:
#   generator: false

nav:
- Home: 'index.md'
- Theory: 'theory.md'
- Examples: 'examples.md'
- Reference:
  - reference/index.md
  - angle_btw: 'reference/angle_btw.md'
  - angle_deltas: 'reference/angle_deltas.md'
  - clucenters: 'reference/clucenters.md'
  - clugen: 'reference/clugen.md'
  - clumerge: 'reference/clumerge.md'
  - clupoints_n: 'reference/clupoints_n.md'
  - clupoints_n_1: 'reference/clupoints_n_1.md'
  - clupoints_n_1_template: 'reference/clupoints_n_1_template.md'
  - cluseed: 'reference/cluseed.md'
  - clusizes: 'reference/clusizes.md'
  - fix_empty: 'reference/fix_empty.md'
  - fix_num_points: 'reference/fix_num_points.md'
  - llengths: 'reference/llengths.md'
  - points_on_line: 'reference/points_on_line.md'
  - rand_ortho_vector: 'reference/rand_ortho_vector.md'
  - rand_unit_vector: 'reference/rand_unit_vector.md'
  - rand_vector_at_angle: 'reference/rand_vector_at_angle.md'
- Development: 'dev.md'