name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: joergbrech/moxunit-action@v1
        with:
          tests: tests/tests_all.m
          src: src
          pkg: statistics
          with_coverage: true
          cover_xml_file: coverage.xml
      - uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml