name: Coverage

on:
  push:
    branches: [ main ]
    paths: [ 'src/**', 'tests/tests_all.m', '.github/workflows/cov.yml' ]
  pull_request:
    branches: [ main ]
    paths: [ 'src/**', 'tests/tests_all.m', '.github/workflows/cov.yml' ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: joergbrech/moxunit-action@v1
        with:
          tests: tests/tests_all.m
          src: src
          pkg: statistics
          with_coverage: true
          cover_xml_file: coverage.xml
      - uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml