name: Docs

on:
  push:
    tags: 'v*'
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
        with:
          lfs: true
      - name: Install Octave and xvfb
        run: |
          sudo apt update
          sudo apt install -y octave octave-statistics xvfb
      - name: Build docs
        run: |
          pip3 install --user --upgrade pip
          pip3 install --user mkdocs-material
          cd docs
          python3 mocdoc.py
          ./run_moc_in_md.sh docs/examples.md
          mkdocs build
      - name: Deploy to GitHub pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: docs/site
